"""fix column name

Revision ID: 26f31c65f00e
Revises: 6c1409d68f1d
Create Date: 2024-06-30 17:21:33.622482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f31c65f00e'
down_revision = '6c1409d68f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('sale_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_data', sa.DATETIME(), nullable=False))
        batch_op.drop_column('sale_date')

    # ### end Alembic commands ###
