version: '3.3'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=development